"""
HTML提取模块 - 从HTML文件提取发布所需内容

HTML extractor module - Extract content from HTML files for publishing.
"""

import sys
import re
import base64
from pathlib import Path
from typing import Dict, List, Optional
from bs4 import BeautifulSoup

# 添加父目录到路径以支持导入config
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import MAX_CONTENT_LENGTH


class HTMLExtractor:
    """HTML内容提取器"""

    def __init__(self):
        """初始化提取器"""
        self.soup: Optional[BeautifulSoup] = None
        self.html_path: Optional[Path] = None

    def extract(self, html_path: str) -> Dict:
        """
        从HTML文件提取所有发布所需内容

        Args:
            html_path: HTML文件路径

        Returns:
            包含title, content, topics, images的字典
        """
        self.html_path = Path(html_path)

        # 验证文件存在
        if not self.html_path.exists():
            raise FileNotFoundError(f"HTML文件不存在: {html_path}")

        # 读取并解析HTML
        with open(self.html_path, 'r', encoding='utf-8') as f:
            html_content = f.read()

        self.soup = BeautifulSoup(html_content, 'html.parser')

        # 提取各部分内容
        result = {
            'title': self._extract_title(),
            'content': self._extract_content(),
            'topics': self._extract_topics(),
            'images': self._extract_base64_images(),
            'document_name': self.html_path.stem
        }

        return result

    def _extract_title(self) -> str:
        """提取标题"""
        title_tag = self.soup.find('title')
        if title_tag:
            title = title_tag.get_text(strip=True)
            # 清理标题中的时间戳等后缀
            title = re.sub(r'_\d{8}_\d{6}$', '', title)
            return title
        return "未命名标题"

    def _extract_content(self) -> str:
        """
        提取正文内容（保留段落结构和h2标题）

        优先查找<div class="content">，如果没有则提取body中的文本
        保留<p>和<h2>标签的段落分隔，维持原始分段
        """
        # 优先查找content区域
        content_div = self.soup.find('div', class_='content')

        if content_div:
            # 移除不需要的标签（但不移除段落结构）
            for tag in content_div.find_all(['script', 'style', 'noscript', 'h1']):
                tag.decompose()
        else:
            # 没有content区域，使用body
            content_div = self.soup.find('body')
            if not content_div:
                content_div = self.soup

        # 提取所有段落和h2标题，保持原始顺序
        paragraphs = content_div.find_all(['p', 'h2'])

        if paragraphs:
            # 提取每个段落的文本，用双换行符连接
            paragraph_texts = []
            for elem in paragraphs:
                text = elem.get_text(strip=True)
                if text:  # 跳过空段落
                    # h2标题添加特殊标记以突出显示
                    if elem.name == 'h2':
                        paragraph_texts.append(f"【{text}】")
                    else:
                        paragraph_texts.append(text)

            cleaned_content = '\n\n'.join(paragraph_texts)
        else:
            # 如果没有<p>标签，使用get_text作为备选
            cleaned_content = content_div.get_text(separator='\n', strip=True)
            # 最小清理
            cleaned_content = re.sub(r'\n{3,}', '\n\n', cleaned_content)

        # 截断过长内容（按段落截断）
        if len(cleaned_content) > MAX_CONTENT_LENGTH:
            cleaned_content = self._truncate_by_paragraphs(cleaned_content, MAX_CONTENT_LENGTH)

        return cleaned_content

    def _clean_and_refine_content(self, raw_content: str) -> str:
        """
        清理和修缮内容（增强版）

        Args:
            raw_content: 原始内容

        Returns:
            清理后的内容
        """
        # 扩展的无关关键词列表
        irrelevant_keywords = [
            'context view',
            'context view source',
            'main scene',
            'main scene:',
            'detail view',
            'detail view:',
            '正文内容',
            '[正文内容]',
            '查看原文',
            '点击查看',
            'read more',
            '转载请注明',
            '版权所有',
            '©',
            'all rights reserved',
            'rights reserved',
            '版权声明',
            '声明',
            '原创',
            'author:',
            'source:',
            'date:',
            'published:',
            'category:',
            'tags:',
            'view source',
            'show source',
            'html source',
            'generated by',
            'created with',
            '分享到',
            'share to',
            'related posts',
            '推荐阅读',
            'you may also like'
        ]

        # 分割成行
        lines = raw_content.split('\n')
        cleaned_lines = []

        # 统计连续空行数量
        empty_line_count = 0

        for line in lines:
            original_line = line
            line = line.strip()

            # 跳过完全空行
            if not line:
                empty_line_count += 1
                # 只保留一个空行（段落分隔）
                if empty_line_count == 1:
                    cleaned_lines.append('')
                continue

            # 重置空行计数（有内容了）
            empty_line_count = 0

            # 跳过单字符行（通常是无意义的符号）
            if len(line) <= 1:
                continue

            # 跳过纯数字或特殊符号行
            if re.match(r'^[\d\s\-_+=<>\/\\|\[\]{}()]*$', line):
                continue

            # 跳过包含无关关键词的行（不区分大小写）
            line_lower = line.lower()
            if any(keyword.lower() in line_lower for keyword in irrelevant_keywords):
                continue

            # 跳过方括号包围的标签（如[正文内容]、[图片]等）
            if re.match(r'^\[.+\]$', line):
                continue

            # 跳过看起来像技术标记或元数据的行
            # 格式如：KEY: VALUE（简短的）
            if re.match(r'^[A-Z_]+:\s*.+', line) and len(line) < 50:
                # 排除一些常见的有效标题格式
                if not re.match(r'^(第[一二三四五六七八九十]+[章节篇]|[\d]+\.)', line):
                    continue

            # 跳过URL链接
            if re.match(r'^https?://', line) or 'http://' in line_lower or 'https://' in line_lower:
                continue

            # 跳过HTML标签残留
            if re.match(r'^<[a-z]', line_lower) or line.endswith('>'):
                continue

            # 修正：清理行内多余空格
            line = re.sub(r'\s+', ' ', line)

            cleaned_lines.append(line)

        # 合并行，使用合理的段落分隔
        cleaned_content = '\n'.join(cleaned_lines)

        # 后处理：清理多余的连续空行（超过1个的空行合并为1个）
        cleaned_content = re.sub(r'\n{3,}', '\n\n', cleaned_content)

        # 清理开头和结尾的空白
        cleaned_content = cleaned_content.strip()

        # 截断过长内容（按段落截断，保持段落完整性）
        if len(cleaned_content) > MAX_CONTENT_LENGTH:
            cleaned_content = self._truncate_by_paragraphs(cleaned_content, MAX_CONTENT_LENGTH)

        return cleaned_content

    def _truncate_by_paragraphs(self, content: str, max_length: int) -> str:
        """
        按段落截断内容（从后往前删除段落，保持段落完整性）

        Args:
            content: 原始内容
            max_length: 最大长度

        Returns:
            截断后的内容
        """
        # 按段落分割（多个连续换行符视为段落分隔）
        paragraphs = re.split(r'\n\s*\n', content)

        # 如果只有一个段落，直接按字符截断
        if len(paragraphs) <= 1:
            return content[:max_length]

        # 从前往后累加段落，直到接近max_length
        result_paragraphs = []
        current_length = 0

        for para in paragraphs:
            para_length = len(para) + 2  # +2 是段落之间的换行符

            if current_length + para_length <= max_length:
                result_paragraphs.append(para)
                current_length += para_length
            else:
                # 这个段落加上会超限，停止添加
                break

        # 如果连第一个段落都超限，直接截断
        if not result_paragraphs:
            return paragraphs[0][:max_length]

        # 用双换行符连接段落
        truncated_content = '\n\n'.join(result_paragraphs)

        return truncated_content

    def _extract_topics(self) -> List[str]:
        """
        提取话题标签

        优先级：
        1. <meta name="keywords"> 标签
        2. 从内容推断
        3. 返回默认话题
        """
        # 尝试从meta标签提取
        meta_keywords = self.soup.find('meta', attrs={'name': 'keywords'})
        if meta_keywords and meta_keywords.get('content'):
            keywords = meta_keywords['content']
            return [kw.strip() for kw in keywords.split(',') if kw.strip()]

        # 从标题和内容推断（简单实现）
        content = self._extract_content()
        title = self._extract_title()

        # 根据内容关键词推断
        inferred_topics = set()

        # 技术相关
        tech_keywords = ['AI', '人工智能', '机器学习', 'Python', 'JavaScript', 'Claude']
        for kw in tech_keywords:
            if kw in content or kw in title:
                inferred_topics.add(kw)

        # 文化相关
        culture_keywords = ['传统文化', '民俗', '非遗', '历史']
        for kw in culture_keywords:
            if kw in content or kw in title:
                inferred_topics.add(kw)

        return list(inferred_topics) if inferred_topics else []

    def _extract_base64_images(self) -> List[Dict]:
        """
        提取图片（支持Base64和本地文件路径）

        Returns:
            图片列表: [{'index': 0, 'format': 'jpeg', 'data': 'base64...'}]
        """
        images = []

        # 查找所有img标签
        img_tags = self.soup.find_all('img')

        for i, img in enumerate(img_tags):
            src = img.get('src', '')

            if not src:
                continue

            if src.startswith('data:image/'):
                # 处理Base64图片
                # 格式: data:image/jpeg;base64,/9j/4AAQ...
                match = re.match(r'data:image/(jpeg|png|jpg|gif);base64,(.+)', src)
                if match:
                    img_format, base64_data = match.groups()
                    images.append({
                        'index': i,
                        'format': img_format,
                        'data': base64_data
                    })
            else:
                # 处理本地文件路径
                try:
                    # 解析相对路径
                    img_path = self.html_path.parent / src

                    if img_path.exists():
                        # 读取图片文件并转换为base64
                        with open(img_path, 'rb') as f:
                            image_data = f.read()
                            base64_data = base64.b64encode(image_data).decode('utf-8')

                            # 根据文件扩展名确定格式
                            img_format = 'jpeg'
                            if img_path.suffix.lower() in ['.png']:
                                img_format = 'png'
                            elif img_path.suffix.lower() in ['.jpg', '.jpeg']:
                                img_format = 'jpeg'
                            elif img_path.suffix.lower() in ['.gif']:
                                img_format = 'gif'

                            images.append({
                                'index': i,
                                'format': img_format,
                                'data': base64_data
                            })
                except Exception as e:
                    # 静默失败，继续处理下一张图片
                    pass

        return images

    def get_document_name(self) -> str:
        """获取文档名称（不含路径和扩展名）"""
        return self.html_path.stem if self.html_path else "unknown"
