#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Video Lines Skill - Extract dialogue from MP4 videos

Part of video-lines skill v2.0.0 - Generated by skill-creator

Usage:
    python main.py video.mp4
    python main.py video.mp4 -o transcript.txt
    python main.py video.mp4 --format clean
    python main.py video.mp4 --format raw
    python main.py video.mp4 --json
"""

import argparse
import json
import os
import sys
from pathlib import Path
from video_transcriber import VideoTranscriber
from transcript_cleaner import TranscriptCleaner, TranscriptEnhancer


def progress_callback(current, total, segment_path, text):
    """Display progress during transcription."""
    segment_name = os.path.basename(segment_path)
    status = "[OK]" if not text.startswith("[") else "[FAIL]"
    print(f"  [{current}/{total}] {segment_name} {status}")


def estimate_processing_time(video_path, segment_duration=25):
    """Estimate processing time based on video duration.

    Args:
        video_path: Path to video file
        segment_duration: Audio segment duration in seconds

    Returns:
        Tuple of (duration_seconds, estimated_minutes)
    """
    try:
        import subprocess
        # Use ffprobe to get video duration
        cmd = [
            "ffprobe",
            "-v", "error",
            "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            video_path
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if result.returncode == 0:
            duration = float(result.stdout.strip())
            # Rough estimate: ~2-3 seconds per segment
            segments = duration / segment_duration
            estimated_minutes = segments * 2.5 / 60
            return duration, estimated_minutes
    except:
        pass
    return None, None


def main():
    parser = argparse.ArgumentParser(
        description="Extract dialogue and transcript text from MP4 videos using AI speech recognition.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s video.mp4
  %(prog)s video.mp4 -o transcript.txt
  %(prog)s video.mp4 --format clean
  %(prog)s video.mp4 --format raw
  %(prog)s video.mp4 --json

Output formats:
  clean  - Pure dialogue text without markers (default)
  raw    - Includes segment markers for reference

For more information, see: .claude/skills/video-lines/SKILL.md
        """
    )

    parser.add_argument(
        "video",
        help="Path to video file (MP4, AVI, MOV, etc.)"
    )

    parser.add_argument(
        "-o", "--output",
        help="Output file path (default: auto-generated based on video name)"
    )

    parser.add_argument(
        "--segment-duration",
        type=int,
        default=25,
        help="Audio segment duration in seconds (default: 25, max: 30)"
    )

    parser.add_argument(
        "--format",
        choices=["clean", "raw"],
        default="clean",
        help="Output format: clean (no markers) or raw (with markers)"
    )

    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results in JSON format"
    )

    parser.add_argument(
        "--keep-markers",
        action="store_true",
        help="Alias for --format raw (kept for backward compatibility)"
    )

    parser.add_argument(
        "--ffmpeg-path",
        help="Path to ffmpeg executable (auto-detected if not specified)"
    )

    parser.add_argument(
        "--no-llm",
        action="store_true",
        help="Skip LLM post-processing (use basic cleaning only)"
    )

    parser.add_argument(
        "--llm-model",
        default="glm-4.6",
        help="LLM model for post-processing (default: glm-4.6)"
    )

    args = parser.parse_args()

    # Validate video file exists
    if not os.path.exists(args.video):
        print(f"[ERROR] Video file not found: {args.video}", file=sys.stderr)
        return 1

    # Check API key - support both environment variable and config files
    api_key = os.environ.get("ZHIPU_API_KEY")
    if not api_key:
        # Try to load from config files
        config_paths = [
            "C:/D/CAIE_tool/LLM_Configs/GLM/apikeyValue2.txt",  # Coding Plan key (preferred)
            "C:/D/CAIE_tool/LLM_Configs/GLM/apikeyValue.txt",   # Primary key
        ]
        for config_path in config_paths:
            if os.path.exists(config_path):
                try:
                    with open(config_path, 'r') as f:
                        api_key = f.read().strip()
                        if api_key:
                            break
                except Exception:
                    pass

        if not api_key:
            print("[ERROR] ZHIPU_API_KEY not found", file=sys.stderr)
            print("Please set it using:", file=sys.stderr)
            print("  export ZHIPU_API_KEY=your-key-here  # Linux/Mac", file=sys.stderr)
            print("  set ZHIPU_API_KEY=your-key-here     # Windows CMD", file=sys.stderr)
            print("  Or create: C:/D/CAIE_tool/LLM_Configs/GLM/apikeyValue.txt", file=sys.stderr)
            return 1

    # Determine output path (default: same directory as source video)
    if args.output:
        output_path = args.output
    else:
        video_path = Path(args.video)
        output_path = str(video_path.parent / f"{video_path.stem}_transcript.txt")

    # Handle --keep-markers alias
    include_markers = args.keep_markers or (args.format == "raw")

    # Estimate processing time
    duration, estimated_minutes = estimate_processing_time(args.video)
    if duration and estimated_minutes:
        duration_min = int(duration // 60)
        duration_sec = int(duration % 60)
        print(f"[INFO] Video duration: {duration_min}m {duration_sec}s")
        print(f"[INFO] Estimated processing time: {estimated_minutes:.1f} minutes")

    try:
        # Initialize transcriber
        print("[INFO] Initializing transcriber...")
        transcriber = VideoTranscriber(
            segment_duration=args.segment_duration,
            ffmpeg_path=args.ffmpeg_path
        )

        # Transcribe video
        print("[INFO] Starting transcription...")
        stats = transcriber.transcribe_video(
            args.video,
            output_path,
            include_markers=include_markers,
            progress_callback=progress_callback
        )

        # Clean output if format is clean
        if args.format == "clean":
            print("[INFO] Cleaning transcript...")
            cleaner = TranscriptCleaner()
            cleaner.clean_file(output_path)

        # LLM post-processing (default: enabled)
        if args.no_llm:
            print("[INFO] Skipping LLM post-processing (--no-llm)")
        else:
            print("[INFO] Running LLM post-processing...")
            try:
                enhancer = TranscriptEnhancer(model=args.llm_model)
                enhanced_content, enhance_stats = enhancer.enhance(
                    open(output_path, 'r', encoding='utf-8').read()
                )

                if enhance_stats.get("success", False):
                    # Write enhanced content back to file
                    with open(output_path, 'w', encoding='utf-8') as f:
                        f.write(enhanced_content)
                    print(f"  LLM enhancement complete ({enhance_stats.get('processing_time_ms', 0):.0f}ms)")
                else:
                    print(f"  [WARN] LLM enhancement failed: {enhance_stats.get('error', 'Unknown error')}")
                    print("  Using original cleaned output")
            except Exception as e:
                print(f"  [WARN] LLM enhancement error: {e}")
                print("  Using original cleaned output")

        # Display results
        print(f"\n[OK] Transcription complete!")
        print(f"  Output file: {output_path}")
        print(f"  Total segments: {stats['total_segments']}")
        print(f"  Valid segments: {stats['valid_segments']}")
        print(f"  Total characters: {stats['total_chars']}")
        print(f"  Valid characters: {stats['valid_chars']}")

        # JSON output
        if args.json:
            result = {
                "success": True,
                "output_file": os.path.abspath(output_path),
                "stats": stats
            }
            print("\n" + json.dumps(result, indent=2, ensure_ascii=False))

        return 0

    except ValueError as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        return 1
    except RuntimeError as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"[ERROR] Unexpected error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
