#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Video Transcriber - Extract speech from MP4 videos using ZhipuAI ASR

Part of video-lines skill v2.0.0 - Generated by skill-creator
"""

import os
import sys
import glob
import time
import subprocess
from pathlib import Path
from zhipuai import ZhipuAI


class VideoTranscriber:
    """Video speech-to-text transcriber using ZhipuAI GLM-ASR"""

    def __init__(self, segment_duration=25, ffmpeg_path=None):
        """Initialize the transcriber.

        Args:
            segment_duration: Audio segment duration in seconds (max 30 for API)
            ffmpeg_path: Optional path to ffmpeg executable (auto-detected if None)
        """
        self.api_key = os.environ.get("ZHIPU_API_KEY")
        if not self.api_key:
            raise ValueError("ZHIPU_API_KEY environment variable not set")

        self.client = ZhipuAI(api_key=self.api_key)
        self.segment_duration = segment_duration

        # Temporary directory
        self.temp_dir = "transcripts/audio_segments"
        os.makedirs(self.temp_dir, exist_ok=True)

        # ffmpeg path (auto-detect)
        if ffmpeg_path is None:
            ffmpeg_path = self._find_ffmpeg()
        self.ffmpeg_path = ffmpeg_path

        if not self.ffmpeg_path:
            raise RuntimeError(
                "ffmpeg not found. Please install ffmpeg or provide the path.\n"
                "Download from: https://ffmpeg.org/download.html"
            )

    def _find_ffmpeg(self):
        """Auto-detect ffmpeg executable from common locations.

        Returns:
            Path to ffmpeg executable or None if not found
        """
        possible_paths = [
            r"C:\D\CAIE_tool\MyAIProduct\gethtml\ffmpeg_temp\ffmpeg-8.0.1-essentials_build\bin\ffmpeg.exe",
            "ffmpeg",
            "/usr/bin/ffmpeg",
            "/usr/local/bin/ffmpeg",
        ]

        for path in possible_paths:
            if path == "ffmpeg":
                try:
                    subprocess.run(
                        ["ffmpeg", "-version"],
                        capture_output=True,
                        timeout=5,
                        check=False
                    )
                    return "ffmpeg"
                except (FileNotFoundError, Exception):
                    continue
            elif os.path.exists(path):
                return path

        return None

    def extract_audio(self, video_path, output_wav):
        """Extract audio from video file using ffmpeg.

        Args:
            video_path: Path to input video file (MP4, AVI, MOV, etc.)
            output_wav: Path to output WAV file

        Returns:
            True if successful

        Raises:
            RuntimeError: If audio extraction fails
        """
        cmd = [
            self.ffmpeg_path,
            "-i", video_path,
            "-vn",  # No video stream
            "-acodec", "pcm_s16le",  # 16-bit PCM (lossless)
            "-ar", "16000",  # 16kHz sample rate (optimal for ASR)
            "-ac", "1",  # Mono channel
            "-y",  # Overwrite output
            output_wav
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=600
        )

        if result.returncode != 0:
            raise RuntimeError(f"Audio extraction failed: {result.stderr}")

        return True

    def segment_audio(self, audio_path):
        """Segment audio into smaller chunks for API processing.

        Args:
            audio_path: Path to input WAV file

        Returns:
            List of segment file paths sorted by segment number

        Raises:
            RuntimeError: If segmentation fails
        """
        cmd = [
            self.ffmpeg_path,
            "-i", audio_path,
            "-f", "segment",
            "-segment_time", str(self.segment_duration),
            "-c", "copy",
            "-reset_timestamps", "1",
            f"{self.temp_dir}/audio_segment_%03d.wav"
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=600
        )

        if result.returncode != 0:
            raise RuntimeError(f"Audio segmentation failed: {result.stderr}")

        # Get all segment files sorted by name
        segments = sorted(glob.glob(f"{self.temp_dir}/audio_segment_*.wav"))
        return segments

    def transcribe_segment(self, segment_path):
        """Transcribe a single audio segment using ZhipuAI ASR.

        Args:
            segment_path: Path to audio segment file

        Returns:
            Transcribed text string

        Raises:
            Exception: If transcription fails
        """
        with open(segment_path, 'rb') as audio_file:
            response = self.client.audio.transcriptions.create(
                model="GLM-ASR-2512",
                file=audio_file
            )
        return response.text

    def transcribe_segment_with_retry(self, segment_path, max_retries=3):
        """Transcribe with exponential backoff retry mechanism.

        Args:
            segment_path: Path to audio segment file
            max_retries: Maximum number of retry attempts (default: 3)

        Returns:
            Transcribed text string

        Raises:
            Exception: If all retries fail
        """
        last_error = None
        for attempt in range(max_retries):
            try:
                return self.transcribe_segment(segment_path)
            except Exception as e:
                last_error = e
                if attempt < max_retries - 1:
                    wait_time = (attempt + 1) * 5  # 5s, 10s, 15s
                    time.sleep(wait_time)

        raise Exception(
            f"Transcription failed after {max_retries} retries: {last_error}"
        )

    def process_all_segments(self, segments, progress_callback=None):
        """Process all audio segments with progress tracking.

        Args:
            segments: List of segment file paths
            progress_callback: Optional callback function for progress updates
                Called with (current, total, segment_path, text_or_error)

        Returns:
            List of transcribed text strings (or error messages for failures)
        """
        results = []
        for i, segment in enumerate(segments, 1):
            try:
                text = self.transcribe_segment_with_retry(segment)
                results.append(text)

                if progress_callback:
                    progress_callback(i, len(segments), segment, text)
            except Exception as e:
                error_msg = f"[Transcription failed: {os.path.basename(segment)}]"
                results.append(error_msg)

                if progress_callback:
                    progress_callback(i, len(segments), segment, error_msg)

        return results

    def merge_results(self, results, output_path, include_markers=True):
        """Merge all transcription results into a single file.

        Args:
            results: List of transcribed text strings
            output_path: Path to output file
            include_markers: If True, include segment markers and separators

        Returns:
            Dictionary with statistics (total_segments, valid_segments, etc.)
        """
        with open(output_path, "w", encoding="utf-8") as f:
            if include_markers:
                # Write with markers
                f.write("=" * 60 + "\n")
                f.write("Video Speech-to-Text Transcription\n")
                f.write("=" * 60 + "\n\n")

                for i, text in enumerate(results, 1):
                    f.write("=" * 60 + "\n")
                    f.write(f"[Segment {i}]\n")
                    f.write("=" * 60 + "\n\n")
                    f.write(text + "\n\n")
            else:
                # Write without markers (clean format)
                for text in results:
                    f.write(text + "\n")

        # Calculate statistics
        total_chars = sum(len(r) for r in results)
        valid_chars = sum(len(r) for r in results if not r.startswith("["))

        return {
            "total_segments": len(results),
            "valid_segments": len([r for r in results if not r.startswith("[")]),
            "total_chars": total_chars,
            "valid_chars": valid_chars
        }

    def transcribe_video(self, video_path, output_path, include_markers=True, progress_callback=None):
        """Complete workflow: extract audio, segment, transcribe, merge.

        Args:
            video_path: Path to input video file
            output_path: Path to output text file
            include_markers: If True, include segment markers in output
            progress_callback: Optional callback for progress updates

        Returns:
            Dictionary with transcription statistics
        """
        # Step 1: Extract audio
        temp_audio = "transcripts/temp_audio.wav"
        self.extract_audio(video_path, temp_audio)

        # Step 2: Segment audio
        segments = self.segment_audio(temp_audio)

        # Step 3: Transcribe all segments
        results = self.process_all_segments(segments, progress_callback)

        # Step 4: Merge results
        stats = self.merge_results(results, output_path, include_markers)

        return stats
