#!/usr/bin/env python3
"""
Requirement Manager v2.0.0 - Track project requirements and their change history.

Enhanced version with:
- Dependencies management (Blocks/Blocked By)
- Acceptance Criteria
- Hierarchical structure (Parent)
- Labels, Milestone, Owner
- Statistics and blocked reports
- Effort tracking (Estimate/Actual)
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, List


class RequirementManager:
    """Manages project requirements in REQUIREMENTS.md file."""

    REQUIREMENTS_FILE = "REQUIREMENTS.md"

    def __init__(self, project_dir: str):
        self.project_dir = Path(project_dir).resolve()
        self.requirements_file = self.project_dir / self.REQUIREMENTS_FILE

    def _get_timestamp(self) -> str:
        return datetime.now().strftime("%Y-%m-%d %H:%M")

    def _get_next_id(self) -> str:
        if not self.requirements_file.exists():
            return "REQ-001"
        content = self.requirements_file.read_text(encoding="utf-8")
        matches = re.findall(r"REQ-(\d+)", content)
        if not matches:
            return "REQ-001"
        return f"REQ-{max(int(m) for m in matches) + 1:03d}"

    def _create_initial_file(self, project_name: str = None) -> None:
        if not project_name:
            project_name = self.project_dir.name
        content = f"""# {project_name} - Requirements

## Overview

This document tracks requirements for the {project_name} project.

## Statistics

- **Total**: 0
- **Active**: 0
- **Completed**: 0
- **Blocked**: 0

## Active Requirements

_No requirements recorded yet._

---

## Completed Requirements

_No completed requirements yet._

---

*Last updated: {self._get_timestamp()}*
*Generated by requirement-trace skill v2.0.0*
"""
        self.requirements_file.write_text(content, encoding="utf-8")

    def _update_statistics(self, content: str) -> str:
        all_reqs = re.findall(r"### (REQ-\d+):", content)
        active = len(re.findall(r"\*\*Status\*\*:\s*Active", content))
        completed = len(re.findall(r"\*\*Status\*\*:\s*Completed", content))
        blocked = len(re.findall(r"\*\*Blocked\*\*:\s*true", content))

        stats = f"""## Statistics

- **Total**: {len(all_reqs)}
- **Active**: {active}
- **Completed**: {completed}
- **Blocked**: {blocked}"""

        pattern = r"## Statistics\n\n- \*\*Total\*\*:.*?(?=\n## )"
        return re.sub(pattern, stats, content, flags=re.DOTALL)

    def _get_req_section_pattern(self, req_id: str) -> str:
        """Return regex pattern to match a requirement section."""
        return rf"(### {req_id}:.*?)(?=\n### REQ-|\n## [A-Z]|\Z)"

    def add_requirement(
        self,
        requirement: str,
        type: str = "feature",
        priority: str = "medium",
        source: str = None,
        description: str = None,
        owner: str = None,
        milestone: str = None,
        labels: List[str] = None,
        parent: str = None,
        blocks: List[str] = None,
        blocked_by: List[str] = None,
        acceptance_criteria: List[str] = None,
        estimate_hours: float = None
    ) -> str:
        if not self.requirements_file.exists():
            self._create_initial_file()

        req_id = self._get_next_id()
        timestamp = self._get_timestamp()

        if not description:
            description = requirement
        if not source:
            source = requirement

        labels_str = ", ".join([f"`{l}`" for l in labels]) if labels else "_None_"
        blocks_str = ", ".join(blocks) if blocks else "None"
        blocked_by_str = ", ".join(blocked_by) if blocked_by else "None"

        ac_lines = "\n".join([f"- [ ] {c}" for c in acceptance_criteria]) if acceptance_criteria else "_No acceptance criteria defined._"

        effort_str = f"\n- **Estimate**: {estimate_hours}h\n- **Actual**: _Not completed_" if estimate_hours else " _Not estimated_"

        title = requirement[:50] + ("..." if len(requirement) > 50 else "")

        req_entry = f"""
### {req_id}: {title}

- **Status**: Active
- **Type**: {type.capitalize()}
- **Priority**: {priority.capitalize()}
- **Created**: {timestamp}
- **Updated**: {timestamp}
- **Owner**: {owner if owner else "_Unassigned_"}
- **Milestone**: {milestone if milestone else "_None_"}
- **Labels**: {labels_str}
- **Parent**: {parent if parent else "_None_"}
- **Source**: {source}
- **Blocked**: false
- **Description**: {description}
- **Effort**:{effort_str}

#### Dependencies
- **Blocks**: {blocks_str}
- **Blocked By**: {blocked_by_str}

#### Acceptance Criteria
{ac_lines}

#### Change History
- {timestamp}: Initial requirement

"""

        content = self.requirements_file.read_text(encoding="utf-8")

        if "_No requirements recorded yet._" in content:
            content = content.replace("_No requirements recorded yet._", req_entry.strip())
        else:
            content = re.sub(r"(## Active Requirements\n)", r"\1" + req_entry, content)

        content = self._update_statistics(content)
        content = re.sub(r"\*Last updated:.*\*", f"*Last updated: {timestamp}*", content)

        self.requirements_file.write_text(content, encoding="utf-8")
        return req_id

    def update_requirement(
        self,
        req_id: str,
        requirement: str = None,
        status: str = None,
        description: str = None,
        owner: str = None,
        milestone: str = None,
        labels: List[str] = None,
        change_note: str = None,
        actual_hours: float = None
    ) -> bool:
        if not self.requirements_file.exists():
            print("Error: Requirements file not found", file=sys.stderr)
            return False

        content = self.requirements_file.read_text(encoding="utf-8")
        pattern = self._get_req_section_pattern(req_id)
        match = re.search(pattern, content, re.DOTALL)

        if not match:
            print(f"Error: Requirement {req_id} not found", file=sys.stderr)
            return False

        req_section = match.group(1)
        timestamp = self._get_timestamp()

        if status:
            req_section = re.sub(r"\*\*Status\*\*:\s*\w+", f"**Status**: {status.capitalize()}", req_section)
        if description:
            req_section = re.sub(r"\*\*Description\*\*:\s*.*", f"**Description**: {description}", req_section)
        if owner:
            req_section = re.sub(r"\*\*Owner\*\*:\s*[^\n]+", f"**Owner**: {owner}", req_section)
        if milestone:
            req_section = re.sub(r"\*\*Milestone\*\*:\s*[^\n]+", f"**Milestone**: {milestone}", req_section)
        if labels:
            labels_str = ", ".join([f"`{l}`" for l in labels])
            req_section = re.sub(r"\*\*Labels\*\*:\s*[^\n]+", f"**Labels**: {labels_str}", req_section)

        req_section = re.sub(r"\*\*Updated\*\*:\s*[\d-]+ [\d:]+", f"**Updated**: {timestamp}", req_section)

        if change_note:
            req_section = re.sub(r"(#### Change History\n)", rf"\1- {timestamp}: {change_note}\n", req_section)

        content = content[:match.start(1)] + req_section + content[match.end(1):]
        content = self._update_statistics(content)
        content = re.sub(r"\*Last updated:.*\*", f"*Last updated: {timestamp}*", content)

        self.requirements_file.write_text(content, encoding="utf-8")
        return True

    def link_requirements(self, req_id: str, link_to: str, link_type: str = "blocks") -> bool:
        if not self.requirements_file.exists():
            print("Error: Requirements file not found", file=sys.stderr)
            return False

        content = self.requirements_file.read_text(encoding="utf-8")
        timestamp = self._get_timestamp()

        if link_type == "blocks":
            # Update source Blocks
            source_pattern = self._get_req_section_pattern(req_id)
            source_match = re.search(source_pattern, content, re.DOTALL)
            if not source_match:
                print(f"Error: Requirement {req_id} not found", file=sys.stderr)
                return False

            source_section = source_match.group(1)
            blocks_match = re.search(r"\*\*Blocks\*\*:\s*([^\n]+)", source_section)
            if blocks_match:
                current = blocks_match.group(1)
                if current == "None":
                    new_value = link_to
                else:
                    if link_to in current:
                        print(f"Warning: {req_id} already blocks {link_to}")
                        return True
                    new_value = f"{current}, {link_to}"
                source_section = re.sub(r"\*\*Blocks\*\*:\s*[^\n]+", f"**Blocks**: {new_value}", source_section)

            source_section = re.sub(r"(#### Change History\n)", rf"\1- {timestamp}: Added dependency - blocks {link_to}\n", source_section)
            content = content[:source_match.start(1)] + source_section + content[source_match.end(1):]

            # Update target BlockedBy and Blocked
            target_pattern = self._get_req_section_pattern(link_to)
            target_match = re.search(target_pattern, content, re.DOTALL)
            if target_match:
                target_section = target_match.group(1)
                blocked_by_match = re.search(r"\*\*Blocked By\*\*:\s*([^\n]+)", target_section)
                if blocked_by_match:
                    current = blocked_by_match.group(1)
                    new_value = req_id if current == "None" else f"{current}, {req_id}"
                    target_section = re.sub(r"\*\*Blocked By\*\*:\s*[^\n]+", f"**Blocked By**: {new_value}", target_section)
                    target_section = re.sub(r"\*\*Blocked\*\*:\s*false", "**Blocked**: true", target_section)
                    content = content[:target_match.start(1)] + target_section + content[target_match.end(1):]

        elif link_type == "blocked-by":
            # Update source BlockedBy and Blocked
            source_pattern = self._get_req_section_pattern(req_id)
            source_match = re.search(source_pattern, content, re.DOTALL)
            if not source_match:
                print(f"Error: Requirement {req_id} not found", file=sys.stderr)
                return False

            source_section = source_match.group(1)
            blocked_by_match = re.search(r"\*\*Blocked By\*\*:\s*([^\n]+)", source_section)
            if blocked_by_match:
                current = blocked_by_match.group(1)
                if current == "None":
                    new_value = link_to
                else:
                    if link_to in current:
                        print(f"Warning: {req_id} is already blocked by {link_to}")
                        return True
                    new_value = f"{current}, {link_to}"
                source_section = re.sub(r"\*\*Blocked By\*\*:\s*[^\n]+", f"**Blocked By**: {new_value}", source_section)
                source_section = re.sub(r"\*\*Blocked\*\*:\s*false", "**Blocked**: true", source_section)

            source_section = re.sub(r"(#### Change History\n)", rf"\1- {timestamp}: Added dependency - blocked by {link_to}\n", source_section)
            content = content[:source_match.start(1)] + source_section + content[source_match.end(1):]

            # Update target Blocks
            target_pattern = self._get_req_section_pattern(link_to)
            target_match = re.search(target_pattern, content, re.DOTALL)
            if target_match:
                target_section = target_match.group(1)
                blocks_match = re.search(r"\*\*Blocks\*\*:\s*([^\n]+)", target_section)
                if blocks_match:
                    current = blocks_match.group(1)
                    new_value = req_id if current == "None" else f"{current}, {req_id}"
                    target_section = re.sub(r"\*\*Blocks\*\*:\s*[^\n]+", f"**Blocks**: {new_value}", target_section)
                    content = content[:target_match.start(1)] + target_section + content[target_match.end(1):]

        content = self._update_statistics(content)
        content = re.sub(r"\*Last updated:.*\*", f"*Last updated: {timestamp}*", content)
        self.requirements_file.write_text(content, encoding="utf-8")
        return True

    def block_requirement(self, req_id: str, reason: str = None) -> bool:
        return self.update_requirement(req_id, change_note=f"Blocked: {reason}" if reason else "Marked as blocked")

    def unblock_requirement(self, req_id: str) -> bool:
        if not self.requirements_file.exists():
            print("Error: Requirements file not found", file=sys.stderr)
            return False

        content = self.requirements_file.read_text(encoding="utf-8")
        pattern = self._get_req_section_pattern(req_id)
        match = re.search(pattern, content, re.DOTALL)

        if not match:
            print(f"Error: Requirement {req_id} not found", file=sys.stderr)
            return False

        req_section = match.group(1)
        timestamp = self._get_timestamp()

        req_section = re.sub(r"\*\*Blocked By\*\*:\s*[^\n]+", "**Blocked By**: None", req_section)
        req_section = re.sub(r"\*\*Blocked\*\*:\s*true", "**Blocked**: false", req_section)
        req_section = re.sub(r"(#### Change History\n)", rf"\1- {timestamp}: Unblocked\n", req_section)

        content = content[:match.start(1)] + req_section + content[match.end(1):]
        content = self._update_statistics(content)
        content = re.sub(r"\*Last updated:.*\*", f"*Last updated: {timestamp}*", content)

        self.requirements_file.write_text(content, encoding="utf-8")
        return True

    def complete_requirement(self, req_id: str, completion_note: str = None) -> bool:
        if not self.requirements_file.exists():
            print("Error: Requirements file not found", file=sys.stderr)
            return False

        content = self.requirements_file.read_text(encoding="utf-8")
        timestamp = self._get_timestamp()

        pattern = self._get_req_section_pattern(req_id)
        match = re.search(pattern, content, re.DOTALL)

        if not match:
            print(f"Error: Requirement {req_id} not found", file=sys.stderr)
            return False

        req_section = match.group(1)
        req_section = re.sub(r"\*\*Status\*\*:\s*\w+", "**Status**: Completed", req_section)

        history_entry = f"- {timestamp}: Marked as completed"
        if completion_note:
            history_entry += f" - {completion_note}"
        req_section = re.sub(r"(#### Change History\n)", rf"\1{history_entry}\n", req_section)

        # Remove from active section
        content = content[:match.start(1)] + content[match.end(1):]
        content = re.sub(r"\n{3,}", "\n\n", content)

        # Add to completed section
        if "_No completed requirements yet._" in content:
            content = content.replace("_No completed requirements yet._", req_section.strip())
        else:
            content = re.sub(r"(## Completed Requirements\n)", r"\1\n" + req_section.strip() + "\n", content)

        content = self._update_statistics(content)
        content = re.sub(r"\*Last updated:.*\*", f"*Last updated: {timestamp}*", content)

        self.requirements_file.write_text(content, encoding="utf-8")
        return True

    def get_statistics(self) -> Dict:
        if not self.requirements_file.exists():
            return {"error": "No requirements file found"}

        content = self.requirements_file.read_text(encoding="utf-8")
        all_reqs = re.findall(r"### (REQ-\d+):", content)
        active = len(re.findall(r"\*\*Status\*\*:\s*Active", content))
        completed = len(re.findall(r"\*\*Status\*\*:\s*Completed", content))
        blocked = len(re.findall(r"\*\*Blocked\*\*:\s*true", content))

        types = {}
        for t in ["Feature", "Bugfix", "Enhancement", "Change"]:
            count = len(re.findall(rf"\*\*Type\*\*:\s*{t}", content))
            if count > 0:
                types[t.lower()] = count

        priorities = {}
        for p in ["High", "Medium", "Low"]:
            count = len(re.findall(rf"\*\*Priority\*\*:\s*{p}", content))
            if count > 0:
                priorities[p.lower()] = count

        blocked_reqs = []
        req_sections = re.findall(r"(### REQ-\d+:.*?)(?=\n### REQ-|\n## [A-Z]|\Z)", content, re.DOTALL)
        for section in req_sections:
            if "**Blocked**: true" in section:
                id_match = re.search(r"(REQ-\d+):", section)
                reason_match = re.search(r"\*\*Blocked By\*\*:\s*([^\n]+)", section)
                if id_match:
                    blocked_reqs.append({
                        "id": id_match.group(1),
                        "blocked_by": reason_match.group(1) if reason_match else "Unknown"
                    })

        return {
            "total": len(all_reqs),
            "active": active,
            "completed": completed,
            "blocked": blocked,
            "by_type": types,
            "by_priority": priorities,
            "blocked_requirements": blocked_reqs
        }

    def get_blocked_report(self) -> str:
        stats = self.get_statistics()
        if stats.get("error"):
            return stats["error"]
        if not stats.get("blocked_requirements"):
            return "No blocked requirements found."

        lines = ["# Blocked Requirements Report", "", f"Total blocked: {stats['blocked']}", ""]
        for req in stats["blocked_requirements"]:
            lines.append(f"## {req['id']}")
            lines.append(f"- **Blocked by**: {req['blocked_by']}")
            lines.append("")
        return "\n".join(lines)

    def list_requirements(self, status: str = None, type: str = None, priority: str = None, blocked: bool = None) -> str:
        if not self.requirements_file.exists():
            return "No requirements file found. Add a requirement first."

        content = self.requirements_file.read_text(encoding="utf-8")
        matches = re.findall(r"(### REQ-\d+:.*?)(?=\n### REQ-|\n## [A-Z]|\Z)", content, re.DOTALL)

        if not matches:
            return "No requirements found."

        results = []
        for req in matches:
            if status:
                status_match = re.search(r"\*\*Status\*\*:\s*(\w+)", req)
                if status_match and status_match.group(1).lower() != status.lower():
                    continue
            if type:
                type_match = re.search(r"\*\*Type\*\*:\s*(\w+)", req)
                if type_match and type_match.group(1).lower() != type.lower():
                    continue
            if priority:
                priority_match = re.search(r"\*\*Priority\*\*:\s*(\w+)", req)
                if priority_match and priority_match.group(1).lower() != priority.lower():
                    continue
            if blocked is not None:
                blocked_match = re.search(r"\*\*Blocked\*\*:\s*(\w+)", req)
                is_blocked = blocked_match and blocked_match.group(1).lower() == "true"
                if is_blocked != blocked:
                    continue

            id_match = re.search(r"(REQ-\d+): ([^\n]+)", req)
            if id_match:
                req_id = id_match.group(1)
                title = id_match.group(2).strip()[:50]
                status_match = re.search(r"\*\*Status\*\*:\s*(\w+)", req)
                req_status = status_match.group(1) if status_match else "Unknown"
                blocked_match = re.search(r"\*\*Blocked\*\*:\s*(\w+)", req)
                is_blocked = blocked_match and blocked_match.group(1).lower() == "true"
                blocked_indicator = " [BLOCKED]" if is_blocked else ""
                results.append(f"- [{req_status}] {req_id}: {title}{blocked_indicator}")

        return "\n".join(results) if results else "No requirements match the specified filters."

    def search_requirements(self, query: str) -> str:
        if not self.requirements_file.exists():
            return "No requirements file found. Add a requirement first."

        content = self.requirements_file.read_text(encoding="utf-8")
        matches = re.findall(r"(### REQ-\d+:.*?)(?=\n### REQ-|\n## [A-Z]|\Z)", content, re.DOTALL)

        if not matches:
            return "No requirements found."

        results = []
        query_lower = query.lower()

        for req in matches:
            if query_lower in req.lower():
                id_match = re.search(r"(REQ-\d+): (.*)", req)
                if id_match:
                    req_id = id_match.group(1)
                    title = id_match.group(2).strip()[:50]
                    status_match = re.search(r"\*\*Status\*\*:\s*(\w+)", req)
                    req_status = status_match.group(1) if status_match else "Unknown"
                    blocked_match = re.search(r"\*\*Blocked\*\*:\s*(\w+)", req)
                    is_blocked = blocked_match and blocked_match.group(1).lower() == "true"
                    blocked_indicator = " [BLOCKED]" if is_blocked else ""
                    results.append(f"- [{req_status}] {req_id}: {title}{blocked_indicator}")

        return "\n".join(results) if results else f"No requirements found matching '{query}'."

    def get_requirement(self, req_id: str) -> Optional[str]:
        if not self.requirements_file.exists():
            return None
        content = self.requirements_file.read_text(encoding="utf-8")
        pattern = self._get_req_section_pattern(req_id)
        match = re.search(pattern, content, re.DOTALL)
        return match.group(1).strip() if match else None


def main():
    parser = argparse.ArgumentParser(description="Manage project requirements (v2.0.0)")
    parser.add_argument("--project-dir", "-p", required=True, help="Path to the project directory")
    parser.add_argument("--action", "-a", required=True,
        choices=["add", "list", "search", "complete", "update", "get", "link", "block", "unblock", "stats", "blocked-report"],
        help="Action to perform")
    parser.add_argument("--requirement", "-r", help="Requirement text")
    parser.add_argument("--id", help="Requirement ID")
    parser.add_argument("--type", "-t", choices=["feature", "bugfix", "enhancement", "change"])
    parser.add_argument("--priority", choices=["high", "medium", "low"])
    parser.add_argument("--source", "-s", help="Original user prompt")
    parser.add_argument("--description", "-d", help="Detailed description")
    parser.add_argument("--owner", "-o", help="Owner/assignee")
    parser.add_argument("--milestone", "-m", help="Milestone/version target")
    parser.add_argument("--labels", "-l", help="Comma-separated labels")
    parser.add_argument("--parent", help="Parent requirement ID")
    parser.add_argument("--blocks", help="Comma-separated IDs this blocks")
    parser.add_argument("--blocked-by", help="Comma-separated IDs blocking this")
    parser.add_argument("--acceptance-criteria", help="Semicolon-separated criteria")
    parser.add_argument("--estimate", type=float, help="Estimated effort in hours")
    parser.add_argument("--actual", type=float, help="Actual effort in hours")
    parser.add_argument("--status", help="New status")
    parser.add_argument("--query", "-q", help="Search query")
    parser.add_argument("--note", "-n", help="Note for completion/update")
    parser.add_argument("--link-to", help="Target requirement ID for link")
    parser.add_argument("--link-type", choices=["blocks", "blocked-by"], default="blocks")
    parser.add_argument("--blocked", action="store_true", help="Filter blocked requirements")
    parser.add_argument("--json", action="store_true", help="Output in JSON format")

    args = parser.parse_args()
    manager = RequirementManager(args.project_dir)

    result = None
    success = False

    if args.action == "add":
        if not args.requirement:
            print("Error: --requirement is required for add action", file=sys.stderr)
            sys.exit(1)
        labels = [l.strip() for l in args.labels.split(",")] if args.labels else None
        blocks = [b.strip() for b in args.blocks.split(",")] if args.blocks else None
        blocked_by = [b.strip() for b in args.blocked_by.split(",")] if args.blocked_by else None
        ac = [c.strip() for c in args.acceptance_criteria.split(";")] if args.acceptance_criteria else None

        req_id = manager.add_requirement(
            requirement=args.requirement,
            type=args.type or "feature",
            priority=args.priority or "medium",
            source=args.source,
            description=args.description,
            owner=args.owner,
            milestone=args.milestone,
            labels=labels,
            parent=args.parent,
            blocks=blocks,
            blocked_by=blocked_by,
            acceptance_criteria=ac,
            estimate_hours=args.estimate
        )
        result = {"success": True, "id": req_id, "message": f"Added requirement {req_id}"}
        success = True

    elif args.action == "list":
        output = manager.list_requirements(status=args.status, type=args.type, priority=args.priority, blocked=args.blocked if args.blocked else None)
        result = {"success": True, "requirements": output}
        success = True

    elif args.action == "search":
        if not args.query:
            print("Error: --query is required for search action", file=sys.stderr)
            sys.exit(1)
        output = manager.search_requirements(args.query)
        result = {"success": True, "results": output}
        success = True

    elif args.action == "complete":
        if not args.id:
            print("Error: --id is required for complete action", file=sys.stderr)
            sys.exit(1)
        success = manager.complete_requirement(args.id, args.note)
        result = {"success": success, "id": args.id, "message": f"Completed requirement {args.id}" if success else f"Failed to complete {args.id}"}

    elif args.action == "update":
        if not args.id:
            print("Error: --id is required for update action", file=sys.stderr)
            sys.exit(1)
        labels = [l.strip() for l in args.labels.split(",")] if args.labels else None
        success = manager.update_requirement(req_id=args.id, status=args.status, description=args.description, owner=args.owner, milestone=args.milestone, labels=labels, change_note=args.note, actual_hours=args.actual)
        result = {"success": success, "id": args.id, "message": f"Updated requirement {args.id}" if success else f"Failed to update {args.id}"}

    elif args.action == "get":
        if not args.id:
            print("Error: --id is required for get action", file=sys.stderr)
            sys.exit(1)
        req = manager.get_requirement(args.id)
        if req:
            result = {"success": True, "requirement": req}
            success = True
        else:
            result = {"success": False, "message": f"Requirement {args.id} not found"}

    elif args.action == "link":
        if not args.id or not args.link_to:
            print("Error: --id and --link-to are required for link action", file=sys.stderr)
            sys.exit(1)
        success = manager.link_requirements(req_id=args.id, link_to=args.link_to, link_type=args.link_type)
        result = {"success": success, "id": args.id, "link_to": args.link_to, "link_type": args.link_type, "message": f"Linked {args.id} {args.link_type} {args.link_to}" if success else "Failed to link"}

    elif args.action == "block":
        if not args.id:
            print("Error: --id is required for block action", file=sys.stderr)
            sys.exit(1)
        success = manager.block_requirement(args.id, args.note)
        result = {"success": success, "id": args.id, "message": f"Blocked requirement {args.id}" if success else f"Failed to block {args.id}"}

    elif args.action == "unblock":
        if not args.id:
            print("Error: --id is required for unblock action", file=sys.stderr)
            sys.exit(1)
        success = manager.unblock_requirement(args.id)
        result = {"success": success, "id": args.id, "message": f"Unblocked requirement {args.id}" if success else f"Failed to unblock {args.id}"}

    elif args.action == "stats":
        stats = manager.get_statistics()
        result = {"success": True, "statistics": stats}
        success = True

    elif args.action == "blocked-report":
        report = manager.get_blocked_report()
        result = {"success": True, "report": report}
        success = True

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if result:
            if success:
                print(f"[OK] {result.get('message', 'Success')}")
                if 'requirements' in result:
                    print(result['requirements'])
                if 'results' in result:
                    print(result['results'])
                if 'requirement' in result:
                    print(result['requirement'])
                if 'statistics' in result:
                    stats = result['statistics']
                    print("\n=== Requirement Statistics ===")
                    print(f"Total: {stats.get('total', 0)}")
                    print(f"Active: {stats.get('active', 0)}")
                    print(f"Completed: {stats.get('completed', 0)}")
                    print(f"Blocked: {stats.get('blocked', 0)}")
                    if stats.get('by_type'):
                        print(f"By Type: {stats['by_type']}")
                    if stats.get('by_priority'):
                        print(f"By Priority: {stats['by_priority']}")
                    if stats.get('blocked_requirements'):
                        print("\nBlocked Requirements:")
                        for req in stats['blocked_requirements']:
                            print(f"  - {req['id']} (blocked by: {req['blocked_by']})")
                if 'report' in result:
                    print(result['report'])
            else:
                print(f"[FAIL] {result.get('message', 'Failed')}", file=sys.stderr)
                sys.exit(1)


if __name__ == "__main__":
    main()
