#!/usr/bin/env python3
"""
Requirement Manager - Track project requirements and their change history.

Usage:
    python requirement_manager.py --project-dir <path> --action add --requirement "text" [options]
    python requirement_manager.py --project-dir <path> --action list [options]
    python requirement_manager.py --project-dir <path> --action search --query "text" [options]
    python requirement_manager.py --project-dir <path> --action complete --id REQ-XXX [options]
    python requirement_manager.py --project-dir <path> --action update --id REQ-XXX --requirement "text" [options]
"""

import argparse
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional


class RequirementManager:
    """Manages project requirements in REQUIREMENTS.md file."""

    REQUIREMENTS_FILE = "REQUIREMENTS.md"

    def __init__(self, project_dir: str):
        self.project_dir = Path(project_dir).resolve()
        self.requirements_file = self.project_dir / self.REQUIREMENTS_FILE

    def _get_timestamp(self) -> str:
        """Get current timestamp string."""
        return datetime.now().strftime("%Y-%m-%d %H:%M")

    def _get_next_id(self) -> str:
        """Get the next available requirement ID."""
        if not self.requirements_file.exists():
            return "REQ-001"

        content = self.requirements_file.read_text(encoding="utf-8")
        matches = re.findall(r"REQ-(\d+)", content)
        if not matches:
            return "REQ-001"

        max_id = max(int(m) for m in matches)
        return f"REQ-{max_id + 1:03d}"

    def _create_initial_file(self, project_name: str = None) -> None:
        """Create initial REQUIREMENTS.md file."""
        if not project_name:
            project_name = self.project_dir.name

        content = f"""# {project_name} - Requirements

## Overview

This document tracks the requirements and feature requests for the {project_name} project.

## Active Requirements

_No requirements recorded yet._

---

## Completed Requirements

_No completed requirements yet._

---

*Last updated: {self._get_timestamp()}*
*Generated by requirement-trace skill*
"""
        self.requirements_file.write_text(content, encoding="utf-8")

    def add_requirement(
        self,
        requirement: str,
        type: str = "feature",
        priority: str = "medium",
        source: str = None,
        description: str = None
    ) -> str:
        """Add a new requirement to the file."""
        if not self.requirements_file.exists():
            self._create_initial_file()

        req_id = self._get_next_id()
        timestamp = self._get_timestamp()

        # Use requirement text as description if not provided
        if not description:
            description = requirement

        # Create source if not provided
        if not source:
            source = requirement

        # Create the requirement entry
        req_entry = f"""
### {req_id}: {requirement[:50]}{"..." if len(requirement) > 50 else ""}

- **Status**: Active
- **Type**: {type.capitalize()}
- **Priority**: {priority.capitalize()}
- **Created**: {timestamp}
- **Source**: {source}
- **Description**: {description}

#### Change History
- {timestamp}: Initial requirement

"""

        content = self.requirements_file.read_text(encoding="utf-8")

        # Find the "Active Requirements" section and insert
        if "_No requirements recorded yet._" in content:
            content = content.replace(
                "_No requirements recorded yet._",
                req_entry.strip()
            )
        else:
            # Insert after "## Active Requirements"
            pattern = r"(## Active Requirements\n)"
            content = re.sub(pattern, r"\1" + req_entry, content)

        # Update timestamp
        content = re.sub(
            r"\*Last updated:.*\*",
            f"*Last updated: {timestamp}*",
            content
        )

        self.requirements_file.write_text(content, encoding="utf-8")
        return req_id

    def update_requirement(
        self,
        req_id: str,
        requirement: str = None,
        status: str = None,
        description: str = None,
        change_note: str = None
    ) -> bool:
        """Update an existing requirement."""
        if not self.requirements_file.exists():
            print(f"Error: Requirements file not found", file=sys.stderr)
            return False

        content = self.requirements_file.read_text(encoding="utf-8")

        # Find the requirement section
        pattern = rf"(### {req_id}:.*?)(### REQ-|## |$)"
        match = re.search(pattern, content, re.DOTALL)
        if not match:
            print(f"Error: Requirement {req_id} not found", file=sys.stderr)
            return False

        req_section = match.group(1)
        timestamp = self._get_timestamp()

        # Update status
        if status:
            req_section = re.sub(
                r"\*\*Status\*\*:\s*\w+",
                f"**Status**: {status.capitalize()}",
                req_section
            )

        # Update description
        if description:
            req_section = re.sub(
                r"\*\*Description\*\*:\s*.*(?=\n)",
                f"**Description**: {description}",
                req_section
            )

        # Add change history entry
        if change_note:
            history_entry = f"- {timestamp}: {change_note}\n"
            req_section = re.sub(
                r"(#### Change History\n)",
                r"\1" + history_entry,
                req_section
            )

        # Update in content
        content = content[:match.start(1)] + req_section + content[match.end(1):]

        # Update timestamp
        content = re.sub(
            r"\*Last updated:.*\*",
            f"*Last updated: {timestamp}*",
            content
        )

        self.requirements_file.write_text(content, encoding="utf-8")
        return True

    def complete_requirement(self, req_id: str, completion_note: str = None) -> bool:
        """Mark a requirement as completed and move to completed section."""
        if not self.requirements_file.exists():
            print(f"Error: Requirements file not found", file=sys.stderr)
            return False

        content = self.requirements_file.read_text(encoding="utf-8")
        timestamp = self._get_timestamp()

        # Find the requirement section
        pattern = rf"(### {req_id}:.*?)(### REQ-|## Completed|## Active)"
        match = re.search(pattern, content, re.DOTALL)
        if not match:
            print(f"Error: Requirement {req_id} not found", file=sys.stderr)
            return False

        req_section = match.group(1)

        # Update status
        req_section = re.sub(
            r"\*\*Status\*\*:\s*\w+",
            "**Status**: Completed",
            req_section
        )

        # Add completion info
        completion_info = f"\n- **Completed**: {timestamp}"
        if completion_note:
            completion_info += f"\n- **Completion Note**: {completion_note}"

        # Add to change history
        history_entry = f"- {timestamp}: Marked as completed"
        if completion_note:
            history_entry += f" - {completion_note}"
        req_section = re.sub(
            r"(#### Change History\n)",
            r"\1" + history_entry + "\n",
            req_section
        )

        # Remove from active section
        content = content[:match.start(1)] + content[match.end(1):]

        # Clean up double newlines
        content = re.sub(r"\n{3,}", "\n\n", content)

        # Add to completed section
        if "_No completed requirements yet._" in content:
            content = content.replace(
                "_No completed requirements yet._",
                req_section.strip()
            )
        else:
            pattern = r"(## Completed Requirements\n)"
            content = re.sub(pattern, r"\1\n" + req_section.strip() + "\n", content)

        # Update timestamp
        content = re.sub(
            r"\*Last updated:.*\*",
            f"*Last updated: {timestamp}*",
            content
        )

        self.requirements_file.write_text(content, encoding="utf-8")
        return True

    def list_requirements(
        self,
        status: str = None,
        type: str = None,
        priority: str = None
    ) -> str:
        """List requirements with optional filters."""
        if not self.requirements_file.exists():
            return "No requirements file found. Add a requirement first."

        content = self.requirements_file.read_text(encoding="utf-8")

        # Extract all requirements (split by ## headers, then find REQ patterns)
        matches = re.findall(r"(### REQ-\d+:.*?)(?=### REQ-|## |\Z)", content, re.DOTALL)

        if not matches:
            return "No requirements found."

        results = []
        for req in matches:
            # Apply filters
            if status:
                status_match = re.search(r"\*\*Status\*\*:\s*(\w+)", req)
                if status_match and status_match.group(1).lower() != status.lower():
                    continue

            if type:
                type_match = re.search(r"\*\*Type\*\*:\s*(\w+)", req)
                if type_match and type_match.group(1).lower() != type.lower():
                    continue

            if priority:
                priority_match = re.search(r"\*\*Priority\*\*:\s*(\w+)", req)
                if priority_match and priority_match.group(1).lower() != priority.lower():
                    continue

            # Extract ID and title (title is on same line as REQ-ID)
            id_match = re.search(r"(REQ-\d+): ([^\n]+)", req)
            if id_match:
                req_id = id_match.group(1)
                title = id_match.group(2).strip()[:50]
                status_match = re.search(r"\*\*Status\*\*:\s*(\w+)", req)
                req_status = status_match.group(1) if status_match else "Unknown"
                results.append(f"- [{req_status}] {req_id}: {title}")

        if not results:
            return "No requirements match the specified filters."

        return "\n".join(results)

    def search_requirements(self, query: str) -> str:
        """Search requirements by keyword."""
        if not self.requirements_file.exists():
            return "No requirements file found. Add a requirement first."

        content = self.requirements_file.read_text(encoding="utf-8")

        # Extract all requirements (split by ## headers, then find REQ patterns)
        matches = re.findall(r"(### REQ-\d+:.*?)(?=### REQ-|## |\Z)", content, re.DOTALL)

        if not matches:
            return "No requirements found."

        results = []
        query_lower = query.lower()

        for req in matches:
            if query_lower in req.lower():
                # Extract ID and title
                id_match = re.search(r"(REQ-\d+): (.*)", req)
                if id_match:
                    req_id = id_match.group(1)
                    title = id_match.group(2).strip()[:50]
                    status_match = re.search(r"\*\*Status\*\*:\s*(\w+)", req)
                    req_status = status_match.group(1) if status_match else "Unknown"

                    # Find matching context
                    lines = req.split("\n")
                    context_lines = [
                        line.strip() for line in lines
                        if query_lower in line.lower() and line.strip()
                    ]
                    context = context_lines[0][:100] if context_lines else ""

                    results.append(f"- [{req_status}] {req_id}: {title}")
                    if context:
                        results.append(f"  Match: {context}...")

        if not results:
            return f"No requirements found matching '{query}'."

        return "\n".join(results)

    def get_requirement(self, req_id: str) -> Optional[str]:
        """Get a specific requirement by ID."""
        if not self.requirements_file.exists():
            return None

        content = self.requirements_file.read_text(encoding="utf-8")

        pattern = rf"(### {req_id}:.*?)(?=### REQ-|## |$)"
        match = re.search(pattern, content, re.DOTALL)

        if match:
            return match.group(1).strip()
        return None


def main():
    parser = argparse.ArgumentParser(
        description="Manage project requirements"
    )
    parser.add_argument(
        "--project-dir", "-p",
        required=True,
        help="Path to the project directory"
    )
    parser.add_argument(
        "--action", "-a",
        required=True,
        choices=["add", "list", "search", "complete", "update", "get"],
        help="Action to perform"
    )
    parser.add_argument(
        "--requirement", "-r",
        help="Requirement text (for add/update)"
    )
    parser.add_argument(
        "--id",
        help="Requirement ID (for complete/update/get)"
    )
    parser.add_argument(
        "--type", "-t",
        choices=["feature", "bugfix", "enhancement", "change"],
        default=None,
        help="Requirement type (default: feature for add action)"
    )
    parser.add_argument(
        "--priority",
        choices=["high", "medium", "low"],
        default=None,
        help="Requirement priority (default: medium for add action)"
    )
    parser.add_argument(
        "--source", "-s",
        help="Original user prompt or context"
    )
    parser.add_argument(
        "--description", "-d",
        help="Detailed requirement description"
    )
    parser.add_argument(
        "--status",
        help="New status (for update)"
    )
    parser.add_argument(
        "--query", "-q",
        help="Search query"
    )
    parser.add_argument(
        "--note", "-n",
        help="Note for completion or update"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output in JSON format"
    )

    args = parser.parse_args()

    manager = RequirementManager(args.project_dir)

    result = None
    success = False

    if args.action == "add":
        if not args.requirement:
            print("Error: --requirement is required for add action", file=sys.stderr)
            sys.exit(1)
        # Set defaults for add action
        req_type = args.type if args.type else "feature"
        req_priority = args.priority if args.priority else "medium"
        req_id = manager.add_requirement(
            requirement=args.requirement,
            type=req_type,
            priority=req_priority,
            source=args.source,
            description=args.description
        )
        result = {"success": True, "id": req_id, "message": f"Added requirement {req_id}"}
        success = True

    elif args.action == "list":
        output = manager.list_requirements(
            status=args.status,
            type=args.type,
            priority=args.priority
        )
        result = {"success": True, "requirements": output}
        success = True

    elif args.action == "search":
        if not args.query:
            print("Error: --query is required for search action", file=sys.stderr)
            sys.exit(1)
        output = manager.search_requirements(args.query)
        result = {"success": True, "results": output}
        success = True

    elif args.action == "complete":
        if not args.id:
            print("Error: --id is required for complete action", file=sys.stderr)
            sys.exit(1)
        success = manager.complete_requirement(args.id, args.note)
        result = {
            "success": success,
            "id": args.id,
            "message": f"Completed requirement {args.id}" if success else f"Failed to complete {args.id}"
        }

    elif args.action == "update":
        if not args.id:
            print("Error: --id is required for update action", file=sys.stderr)
            sys.exit(1)
        success = manager.update_requirement(
            req_id=args.id,
            requirement=args.requirement,
            status=args.status,
            description=args.description,
            change_note=args.note
        )
        result = {
            "success": success,
            "id": args.id,
            "message": f"Updated requirement {args.id}" if success else f"Failed to update {args.id}"
        }

    elif args.action == "get":
        if not args.id:
            print("Error: --id is required for get action", file=sys.stderr)
            sys.exit(1)
        req = manager.get_requirement(args.id)
        if req:
            result = {"success": True, "requirement": req}
            success = True
        else:
            result = {"success": False, "message": f"Requirement {args.id} not found"}

    if args.json:
        import json
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        if result:
            if success:
                print(f"[OK] {result.get('message', 'Success')}")
                if 'requirements' in result:
                    print(result['requirements'])
                if 'results' in result:
                    print(result['results'])
                if 'requirement' in result:
                    print(result['requirement'])
            else:
                print(f"[FAIL] {result.get('message', 'Failed')}", file=sys.stderr)
                sys.exit(1)


if __name__ == "__main__":
    main()
